#!/usr/bin/env python3
"""
Create DPO preference pairs from the existing SFT dataset.

Input:
    data/processed/{snips,atis}_{train,validation}_pairs_json_sft.jsonl

Each input row:
{
    "dataset": "...",
    "input": "...",
    "target": "<correct JSON>"
}

Output:
    data/processed/{snips,atis}_{train,validation}_pairs_dpo.jsonl

Each output row:
{
    "prompt": "...",
    "chosen": "...",
    "rejected": "..."
}

The rejected output is generated by automatically corrupting the
gold structured output.
"""

from __future__ import annotations
from sft_train import PROMPT_TEMPLATE

import argparse
import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SEED = 455


# ---------------------------------------------------------------------
# Corruption functions
# ---------------------------------------------------------------------

def corrupt_intent(example):
    """Replace the intent with another valid intent."""
    intents = example["intent_labels"]

    if len(intents) <= 1:
        return example["target"]

    gold = json.loads(example["target"])

    current = gold["intent"]
    candidates = [x for x in intents if x != current]

    gold["intent"] = random.choice(candidates)

    return json.dumps(gold, ensure_ascii=False, separators=(",", ":"))


def corrupt_slot_value(example):
    """Modify one slot value."""

    gold = json.loads(example["target"])

    slots = gold.get("slots", [])

    if not slots:
        return example["target"]

    idx = random.randrange(len(slots))

    slots[idx]["value"] = slots[idx]["value"] + "_wrong"

    return json.dumps(gold, ensure_ascii=False, separators=(",", ":"))


def remove_slot(example):
    """Delete one slot."""

    gold = json.loads(example["target"])

    slots = gold.get("slots", [])

    if len(slots) == 0:
        return example["target"]

    slots.pop(random.randrange(len(slots)))

    return json.dumps(gold, ensure_ascii=False, separators=(",", ":"))


def add_fake_slot(example):
    """Insert an invalid slot."""

    gold = json.loads(example["target"])

    gold.setdefault("slots", []).append(
        {
            "name": "fake_slot",
            "value": "unknown"
        }
    )

    return json.dumps(gold, ensure_ascii=False, separators=(",", ":"))


# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------

def load_labels(path):
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]


def load_jsonl(path):
    rows = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if line:
                rows.append(json.loads(line))

    return rows


def save_jsonl(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def build_dataset(dataset, split, data_dir):

    input_path = (
        data_dir /
        f"{dataset}_{split}_pairs_json_sft.jsonl"
    )

    output_path = (
        data_dir /
        f"{dataset}_{split}_pairs_dpo.jsonl"
    )

    intent_labels = load_labels(
        data_dir / f"{dataset}_intent_labels.txt"
    )

    slot_labels = load_labels(
        data_dir / f"{dataset}_slot_labels.txt"
)


    rows = load_jsonl(input_path)

    if not rows:
        raise ValueError(f"No examples found in {input_path}")

    output_rows = []

    corruptions = [
        corrupt_intent,
        corrupt_slot_value,
        remove_slot,
        add_fake_slot,
    ]

    for row in rows:
        required = {"input", "target"}
        if not required.issubset(row):
            raise KeyError(f"Expected keys {required}, got {row.keys()}")

        example = {
            "target": row["target"],
            "intent_labels": intent_labels,
        }

        rejected = random.choice(corruptions)(example)

        output_rows.append(
            {
                "prompt": PROMPT_TEMPLATE.format(
                    intent_labels=intent_labels,
                    slot_labels=slot_labels,
                    request=row["input"],
                ),
                "chosen": row["target"],
                "rejected": rejected
            }
        )

    save_jsonl(output_path, output_rows)

    print(
        f"Wrote {len(output_rows)} examples -> {output_path}"
    )


def main():

    random.seed(SEED)

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--dataset",
        choices=["snips", "atis", "both"],
        default="both",
    )

    parser.add_argument(
        "--split",
        choices=["train", "validation"],
        default="train",
    )

    parser.add_argument(
        "--data_dir",
        default="data/processed",
    )

    args = parser.parse_args()

    data_dir = Path(args.data_dir)

    datasets = (
        ["snips", "atis"]
        if args.dataset == "both"
        else [args.dataset]
    )

    for ds in datasets:
        build_dataset(ds, args.split, data_dir)


if __name__ == "__main__":
    main()